window.siteContent = {
  now: [
    {
      status: "building",
      text: "继续完善个人网站，把真实项目、实验和过程整理进去。",
      href: "#lab",
    },
    {
      status: "learning",
      text: "更系统地使用 Codex、Agent 和 Git 工作流，而不只是一轮轮 prompting。",
      href: "#garden",
    },
    {
      status: "exploring",
      text: "研究个人 AI 工具、自动化，还有一些因为好奇而开始的小实验。",
      href: "#lab",
    },
    {
      status: "thinking",
      text: "认真想清楚，什么样的工作和长期方向更适合自己。",
      href: "#about",
    },
  ],
  labs: [
    {
      id: "doupo-analysis",
      caseStudy: "lab/doupo-analysis/",
      title: "doupo-analysis",
      eyebrow: "RUNTIME RABBIT HOLE",
      status: "experiment",
      featured: true,
      repo: "https://github.com/hxy-asdw/doupo-analysis",
      summary: "我本来只是想知道这个小游戏到底有多难成帝。后来我有了一个离线实验室、固定 seed、批量模拟和比最开始更多的问题。",
      question: "一个看不见全貌的运行时行为，能不能在本地被重复观察？",
      whatBuilt: "一个不连接真实服务的离线分析环境，用 seed、instrumentation 和 batch simulation 把一次观察变成可以比较的过程。",
      whatHappened: "边界越清楚，能问的问题反而越多；有些直觉只有在批量运行后才站得住。",
      nextQuestion: "还有哪些差异来自实验模型本身，而不是被观察的行为？",
    },
    {
      id: "excel-data-report",
      title: "excel-data-report",
      eyebrow: "AGENT RELIABILITY LAB",
      status: "building",
      featured: false,
      repo: "https://github.com/hxy-asdw/excel-data-report",
      summary: "我不太相信 Agent 算出来的数字，于是开始一层一层给它加检查。",
      question: "一个 Agent 的分析，怎样才能留下足够多可以回看的痕迹？",
      whatBuilt: "一个从 Excel / CSV 到结构化 HTML 报告的 Python 工作流：规划、确定性分析、图表、复核和渲染被拆成可以检查的阶段。",
      whatHappened: "质量门让错误更容易被发现，也让我更清楚哪些判断不能交给模型临场发挥。",
      nextQuestion: "怎样记录失败案例，才能知道检查真的减少了错误，而不只是让流程变长？",
    },
    {
      id: "limitless",
      title: "limitless",
      eyebrow: "TOY EXPERIMENT",
      status: "paused",
      featured: false,
      repo: "https://github.com/hxy-asdw/limitless",
      summary: "把 DNA、混沌和 cipher 放进同一个小实验里，看看它们会发生什么。它不是安全密码学实现。",
      question: "几个不太应该随便混在一起的想法，会不会产生有意思的行为？",
      whatBuilt: "一个带测试的非标准 toy experiment，保留了假设、限制和实验残留。",
      whatHappened: "它没有变成可用系统，但留下了一种很难归类、所以值得保留的好奇心。",
      nextQuestion: "如果继续做，应该先澄清实验边界，而不是继续堆概念。",
    },
  ],
  garden: [
    {
      id: "workflow-not-prompts",
      href: "garden/workflow-not-prompts/",
      date: "2026-09-09",
      status: "growing",
      title: "第一次认真用 Codex 做一个长期项目，我发现最重要的不是 Prompt。",
      summary: "从想到什么就让它改，到把工作拆成能检查、能回退的小任务。一次个人网站开发中的学习笔记。",
      body: "我还在学习怎样和 Agent 一起维护一个项目。这篇记下的是目前开始有用的一些习惯。",
    },
    {
      id: "olist-rabbit-hole",
      date: "2026",
      status: "growing",
      title: "一个订单延迟问题，为什么最后把我带到了复购率？",
      summary: "从 Olist 的订单延迟开始，一路绕到复购、卖家、地区和那些还没有完全解释清楚的数字。",
      body: "这不是一份商业案例，而是一条分析路径：一个问题先变成几个指标，再变成更多问题。",
    },
    {
      id: "building-this-corner",
      date: "2026",
      status: "seed",
      title: "Building this corner of the internet",
      summary: "GitHub Pages → Portfolio → Apple Design Skill → Digital Garden → just for fun。",
      body: "这是一篇 seed。以后用来记录这个网站怎样慢慢从展示项目，变成一个愿意长期回来的地方。",
    },
  ],
  sideQuests: [
    {
      title: "Recharts",
      state: "Merged",
      summary: "一个本来可以忽略的 Tooltip 边界问题，最后被我一路追到了测试和 upstream。",
      link: "https://github.com/recharts/recharts/pull/7573",
    },
    {
      title: "Storybook",
      state: "Merged",
      summary: "一个系统深色模式和浅色主题之间的小冲突，最后也进入了 upstream。",
      link: "https://github.com/storybookjs/storybook/pull/35541",
    },
  ],
};
